name: test cicd

on: 
  push:
    branches:
    - build

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup java
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: microsoft

    # - name: setup maven
    #   uses: setup-maven/maven@v4
