name: test cicd

on: 
  push:
    branches:
    - build

jobs:
  compile: 
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: setup java
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: microsoft
        cache: maven

    

    - name: build maven and install maven
      run: |
        sudo apt update -y && sudo apt install maven -y
        mvn compile

  security-checks: 
    runs-on: self-hosted
    needs: compile
    steps:
    - uses: actions/checkout@v4

    # - name: setup java
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: 21
    #     distribution: microsoft
    #     cache: maven

    - name: install trivy
      run: |
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install -y trivy

    - name: trivy scan
      run: trivy fs --format table -o fs-report.json .

    - name: Gitleaks Installation
      run: sudo apt install gitleaks -y
      
    - name: Gitleaks Code Scan
      run: gitleaks detect source .
   
