name: test cicd

on: 
  workflow_dispatch

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup java
      uses: actions/setup-java@v4
      with:
        java-version: latest
        distribution: OpenJDK

    # - name: setup maven
    #   uses: setup-maven/maven@v4
